### ISSUE TITLE
False positives on Link text feature

### ISSUE THREAD

**Issue by MattSnowOregonGov** [Khan/tota11y#101]
On most of my websites, we are receiving the following error:

*The text "" is unclear without context and may be confusing to screen readers. Consider rearranging the <a></a> tags or including special screen reader text.*

**Steps to Reproduce**

1. Visit http://staging.apps.oregon.gov/ode
2. Add the Tota11y feature by way of the bookmarklet
3. Activate the Tota11y
4. Enable the Link text feature

You'll see ~25 errors, all of which are false positives.

Thanks for the help!

**Comment by jdan** [comment]
Heya @MattSnowOregonGov,

You should be good to go now! The issue was that we were (rather surprisingly) including hidden links in the audit. So when a dropdown menu has `display: none`, the internal [Accessibility Developer Tools](https://github.com/GoogleChrome/accessibility-developer-tools) "text alternatives" function returns null for the link text.

30dc0fdaa597157cb458ea6d53f127d462764c53 fixed this issue. I went ahead and pushed a new tota11y build so the bookmarklet should just work(TM).

Let me know if you run into anything else. Thanks again for the detailed repro - that's always super helpful.

**Comment by MattSnowOregonGov** [comment]
That's fantastic and totally makes sense. I just checked and can confirm that it no longer reports those false positives! Thank you for for your quick response!

- Matt
