### ISSUE TITLE
Missing some sort of "confirmation" for 0 errors, empty summary

### ISSUE THREAD

**Issue by jdan** [Khan/tota11y#13]
http://jordanscales.com/

![image](https://cloud.githubusercontent.com/assets/287268/8114251/41f2c03c-1041-11e5-8177-770f88e225bd.png)

"Headings" produces an empty summary. Clicking "Labels" does, well, nothing. Expected because there are no inputs, but maybe a little strange.

**Comment by ankitaggarwal011** [comment]
Agreed. A simple "Congratulations. All good!" message would suffice. Are you working on the change?

I read the project, I think a simple detection for 0 errors here: https://github.com/Khan/tota11y/blob/master/plugins/shared/info-panel/index.js#L197 would do the job.
@jdan

**Comment by ankitaggarwal011** [comment]
![noerror-message](https://cloud.githubusercontent.com/assets/4436850/8430885/9444e656-1f52-11e5-9689-e7d46cf4dcc6.png)

I try to solve this. Does this look good in case of no error? What do you think? @jdan

**Comment by jdan** [comment]
@ankitaggarwal011 Thanks for the mockup :) Design-wise it's pretty solid - i'd like the panel to be a little shorter though. Maybe ditch the panel all together for a small green box in the bottom right corner. Unfortunately it's a little confusing because the landmarks plugin will *never* report any errors.

I think we'll need a higher-level solution here where plugins can claim whether or not they'll be reporting errors. I'll likely end up working this into #20.

```js
tota11y.addPlugin('my-plugin', {
    reportsErrors: true,
    run: function() {
        // ...
    },
    cleanup: function() {
        // ...
    }
});
```

**Comment by ankitaggarwal011** [comment]
@jdan , Thanks! I think keep the panel uniform for all plugins would be better UX decision, else It would be confusing. Since, in the test case only the Landmarks plugin showed no errors, I used it to demonstrate the design. However, I have just added code in info-panels/index.js to catch the case where the errors are zero (it's not plugin specific). This will be in all the cases where the number of errors are zero.

I will push and share the code on my forked version for clarity.

I agree that ultimately you should move to the approach where developers can add plugin with a specific API which has the flexibility whether to show summary, errors, or some other tabs they would like.

**Comment by ankitaggarwal011** [comment]
I pushed these changes on a separate branch in my forked version, https://github.com/ankitaggarwal011/tota11y/commit/f6a63a6d49ffda1f899043c69b455cb09a38025c

What do you think? @jdan
