### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by imcodingideas** [Khan/tota11y#200]
Hello,

My work allows me to work 20% of my time on learning and open source. I use tota11y, but no one is working on it. We have some pretty good PRs here but no one is working on getting this approved.

https://github.com/Khan/tota11y/pull/175
https://github.com/Khan/tota11y/pull/179

Whats the plan here? I could fork it but I would prefer to contribute here. If I do work, Im concerned my work would get merged in. Thoughts, feedback?

**Comment by Skeletonxf** [comment]
Several years ago I build an [addon on top of tota11y](https://addons.mozilla.org/en-GB/firefox/addon/totally-automated-a11y-scanner/) which continues to work since it's applied to a webpage via browser addons instead of a bookmarklet. I still use it but it's been in maintenance mode more or less as soon as I finished it since I don't do web development day to day anymore.

I would also prefer to contribute the extensions I wrote into that addon back to here instead of forking (I opened an issue for this several years ago but it was never replied to https://github.com/Khan/tota11y/issues/152).

Given bookmarklets are not as viable now https://github.com/Khan/tota11y/issues/178 a browser addon may be a more suitable way to continue work on tota11y, either a fully integrated addon like I built, or a addon that just injects the tota11y script into a page like several other existing addons.

Given Khan require a CLA signature to accept commits I'm a little concerned that if someone forks tota11y, even though the fork may continue to be MIT licensed, Khan would probably not be able to integrate the changes back without cooperation? If a fork received pull requests from additional contributors it might become impossible to get everyone to sign the CLA to bring the code back here.

**Comment by somewhatabstract** [comment]
Hi folks! 

I am so sorry for not responding sooner. It was a priority for me a while back to get tota11y up-to-date and address some of the various PRs and vulnerabilities that it has. However, in that time, my bandwidth for this work has diminished to near nothing and my priorities have shifted. As I was the only one focused on working on it, that has led to the current state of affairs.

Given that there are browser extensions such as Axe Dev Tools and Accessibility Insights that provide more up-to-date support for many of the things that tota11y aimed to address, it is looking increasibly likely that we won't be updating tota11y further.

Given the bandwidth available, the options we have appear to be to archive this repository, leaving folks to use their own forks as they are able, or, if there are folks willing to take ownership of the project and the work to get things up-to-date, consider moving this to its own organization and letting responsible community volunteers take over the management and maintenance. While this decision ultimately remains with Khan Academy, input from those that are still interested in this project would be valuable, so please comment and let us know what you think.

Again, I apologise for having been unable to keep up with the work this project has needed, and for not responding to folks in a timely manner. It is really wonderful to see the interest this project still garners. It would be amazing if it found new life, though that requires someone to take ownership as we are unable to provide resources at this time.

Jeff
Khan Academy

**Comment by sillero** [comment]
Hi Jeff,

I work at Trello (Atlassian), I am one of the folks involved in a11y inside Trello, and among other internal a11y testing tools I added a way to dynamically import tota11y from our hidden dev toolbar.

I can't speak for Atlassian/Trello, but I'm personally invested on keeping this project going, been a fan of it for years. I like how it can be used to complement more robust a11y tools, and it has great usability even non-developers how would probably struggle to run other tools. I like how visual it gets, and I think that's the biggest win for tota11y, and I would love to keep that.

I understand that there's need for dependency updates, bug fixes, maybe some modernizing and feature updates, but I appreciate I can also run this in almost any browser without need for extension installation which can be bothersome when dealing with managed computers in big companies.

I can personally take ownership of this project if y'all are interested.

**Comment by sillero** [comment]
Bumping to reiterate and make sure people got notified. Thanks.
cc @somewhatabstract

**Comment by somewhatabstract** [comment]
@silero I cannot give a definitive decision yet or a solid timeline, but you offer will be taken into consideration when a decision is made. Thank you for stepping up :)
