### ISSUE TITLE
Hacker news displays zero information for headings tab (also slowness)

### ISSUE THREAD

**Issue by krainboltgreene** [Khan/tota11y#31]
Blank summary page

Seems to run real slow as well, tested against the tota11y thread.

**Comment by jdan** [comment]
#13 covers the empty case. The summary is blank because there are no errors on the page.

As for slowness: a site with as many links as a crowded HN thread (e.g. https://news.ycombinator.com/item?id=9803043) should be expected to stall a bit when scanning the entire document. Particularly slow operations like annotating (i.e. the little labels you see tota11y place next to tags - those cause reflows) are rendered in quick bursts to keep 60 frames.

Here's the code: https://github.com/Khan/tota11y/blob/master/plugins/shared/annotate/index.js#L28-76

But for things like evaluating link text (which hangs for about 800ms on my machine for a crowded HN thread), there's just a lot of code running.

I'm not entirely sure how we could optimize that, but I've attached a profile report below. We spend a lot of time in Accessibility DevTools' `relevantElementMatcher` and `isElementOrAncestorHidden`. Maybe we could knock off some time there if we looked upstream, but I'm skeptical.

![image](https://cloud.githubusercontent.com/assets/287268/8430274/f96589a0-1efd-11e5-8111-a0d507c614a4.png)

What do you think? If you're seeing pages hang for more than a second, or crashing, that's a bigger issue we should probably look into.

**Comment by krainboltgreene** [comment]
I'll check on more sites, but agreed about the user generated content nature issue.

I'm happy to close the issue, and I really appreciate the tool.

**Comment by jdan** [comment]
Cool :) I'll close for now - but feel free to update here if you find anything jarring. Thanks for the kind words!
