### ISSUE TITLE
Toolbar plugin selection should indicate radio buttons

### ISSUE THREAD

**Issue by jgardella** [Khan/tota11y#55]
The plugin selection in the toolbar essentially functions as a group of radio buttons, as only one plugin can be selected at a time. However, the graphic for when a plugin is selected is a white check in a green circle, which indicates they might function as checkboxes, allowing multiple plugins to be selected simultaneously. When I used tota11y for the first time, I thought I could select multiple plugins because of this. Maybe it would be clearer to remove the check and just have a green circle, or something else that suggests radio button more than checkbox.

**Comment by jdan** [comment]
It's not a radio because you can uncheck, and it's not a checkbox because you can only have one selected at a time - so we met in the middle :) A radio with a checkmark!

I agree that the check mark can probably be safely removed, but I'm hesitant to change it right now. I'm doing some a11y work on a separate branch, which includes a bunch of focus styling so I may include it there.
