### ISSUE TITLE
Buttons does not works after the last update (except the heading button)

### ISSUE THREAD

**Issue by Blagada** [Khan/tota11y#91]
Hello, after the last update of the chrome extension (1.3), all the buttons does not works, except the heading button) on my site. You can try it there : http://ici.radio-canada.ca/

If someone have the same problem? Do you know what to do to fix this?

Also, when we have a image inside a link (with a explicit alternative text), the tool still put an error but is not.

If you have any question about my issues, please let me know!
Thanks,

**Comment by jdan** [comment]
Hey @Blagada,

The extension is maintained by someone else, but I imagine any errors are probably our fault. Do you have a screenshot of your browser console that I could see? Also, if you could point me to a URL to test (no worries if you can't!) that would be very helpful.

Thanks for reporting - sorry for the inconvenience :(

**Comment by Blagada** [comment]
Hello ^_^! 
This is the error I find on my browser console :  tota11y.min.js:40 Uncaught TypeError: Cannot read property 'properties' of undefined.

And you can try it by your self there : http://ici.radio-canada.ca/

Thanks for your response. Your chrome extension is really useful for us ^_^!

**Comment by jdan** [comment]
Hey @Blagada,

Looks like you're using requirejs - which unfortunately causes [Accessibility Developer Tools](https://github.com/GoogleChrome/accessibility-developer-tools) (which powers tota11y) to break. This issue was reported in #85, but thank you for the extra data point.

I'm going to close this issue as a duplicate, but please follow along in #85 and we'll be sure to fix it soon. 

Again, sorry for the trouble :(

**Comment by Blagada** [comment]
Oki, thank you for your help!
